### ISSUE TITLE
Script doesnt load

### ISSUE THREAD

**Issue by RawrUniversal** [Addict0919/Addict-Script_2t1#1]
![image](https://user-images.githubusercontent.com/7830406/221248191-0d5b0e48-92e5-49d0-871e-1212da5396c9.png)

**Comment by Addict0919** [comment]
Thank you will look into this soon.

**Comment by Addict0919** [comment]
All fixed!!! 👯

**Comment by RawrUniversal** [comment]
I forgot to add but the write bit also breaks. loading it like 5 times makes it works. 
![image](https://user-images.githubusercontent.com/7830406/222526659-4271f9c9-e8ea-48e6-a3ac-c4722d00cbdc.png)

**Comment by RawrUniversal** [comment]
also its still doing it on load. 
![image](https://user-images.githubusercontent.com/7830406/222527580-82ebf973-7ec8-450c-96f2-be74e82a4d15.png)

**Comment by RawrUniversal** [comment]
[Default.txt](https://github.com/Addict0919/Addict-Script_2t1/files/10875028/Default.txt)
This is my profile config

**Comment by Addict0919** [comment]
> [Default.txt](https://github.com/Addict0919/Addict-Script_2t1/files/10875028/Default.txt) This is my profile config

I uploaded a fix my friend did for us. Try downloading now sorry about this too.

**Comment by Addict0919** [comment]
I have a discord server you can join too add me first, Candypie#1934

**Comment by RawrUniversal** [comment]
why did you ban me? i am so confused.

**Comment by Addict0919** [comment]
> why did you ban me? i am so confused.

You seem like someone I do not like too suspicious, can't risk my server being terminated again.

**Comment by RawrUniversal** [comment]
> > why did you ban me? i am so confused.
> 
> You seem like someone I do not like too suspicious, can't risk my server being terminated again.

I dont know them at all.... i dont even know who you are talking about.

**Comment by RawrUniversal** [comment]
i dont even use stand. i use 2t1 and phantom

**Comment by RawrUniversal** [comment]
How paranoid are you to ban a random person with a REALLY old account? wouldnt they use a new account?
